language: java
install: skip

dist: trusty

jdk:
  - oraclejdk8

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer
  
script:
  - ./gradlew googleJavaFormat
  - ./gradlew build
  - ./gradlew test 
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

